//! Bake mate expression RGB keyframes for ESP offline playout (60panels).
//!
//!   cargo run -p glowbe-runtime -- bake-offline-mate

use std::fs;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

use crate::mate::{
    self, FaceFrame, FaceFrameParams, Modulation, PresetRegistry, MATE_MIN_LED_COUNT,
};
use crate::media;

const EXPR_IDS: [&str; 4] = ["happy", "surprised", "sad", "love"];
/// Mate tour ships only on 60panels (`GLOWBE_LOCAL_HAS_MATE`); 15panels uses geom only.
const LAYOUTS: [&str; 1] = ["geodesic-2v-60"];

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("runtime crate parent")
        .to_path_buf()
}

fn fmt_bytes(rgb: &[u8], per_line: usize) -> String {
    let mut parts = Vec::new();
    for chunk in rgb.chunks(per_line) {
        let line = chunk
            .iter()
            .map(|b| format!("{b}"))
            .collect::<Vec<_>>()
            .join(", ");
        parts.push(format!("    {line},"));
    }
    parts.join("\n")
}

fn bake_layout(compiled_dir: &Path, layout_id: &str, out_path: &Path) -> Result<()> {
    let layout = media::load_layout_uv(compiled_dir, layout_id)
        .with_context(|| format!("load ledmap {layout_id}"))?;
    anyhow::ensure!(
        layout.led_count >= usize::from(MATE_MIN_LED_COUNT),
        "{layout_id}: led_count {} < mate minimum",
        layout.led_count
    );

    let mut leds = layout.leds.clone();
    leds.sort_by_key(|l| l.i);
    let uv: Vec<(f32, f32)> = leds.iter().map(|l| (l.u, l.v)).collect();
    // Offline mate face sits 90° clockwise from default front (+X → −Z, RH +Y yaw).
    let mut frame_params = FaceFrameParams::default();
    frame_params.yaw_deg = 90.0;
    let frame = FaceFrame::from_params(frame_params);
    // Match offline geom tables (FRONT_YAW_DEG = 0 in tools/esp-local-tables.ts).
    let samples = mate::build_face_samples_yawed(&uv, &frame, 0.0);
    let registry =
        PresetRegistry::load(Path::new("/nonexistent")).context("load builtin mate presets")?;

    let n = layout.led_count;
    let mut frames: Vec<Vec<u8>> = Vec::with_capacity(EXPR_IDS.len());
    for id in EXPR_IDS {
        let expr = registry
            .get(id)
            .with_context(|| format!("missing preset {id}"))?;
        let mut rgb = vec![0u8; n * 3];
        mate::render(&samples, &frame, expr, &Modulation::default(), &mut rgb);
        frames.push(rgb);
    }

    let mut body = String::new();
    body.push_str("// Auto-generated by offline_mate_bake — do not edit.\n");
    body.push_str("//   cargo run -p glowbe-runtime -- bake-offline-mate\n");
    body.push_str("#pragma once\n\n");
    body.push_str("#include <Arduino.h>\n\n");
    body.push_str("namespace glowbe::local_mate {\n\n");
    body.push_str(&format!("constexpr uint16_t kLedCount = {n};\n"));
    body.push_str(&format!(
        "constexpr uint8_t kExprCount = {};\n",
        EXPR_IDS.len()
    ));
    body.push_str("constexpr const char* kExprIds[] = {\n");
    for id in EXPR_IDS {
        body.push_str(&format!("  \"{id}\",\n"));
    }
    body.push_str("};\n\n");
    body.push_str(&format!(
        "static const uint8_t kFrames[{}][{}] PROGMEM = {{\n",
        EXPR_IDS.len(),
        n * 3
    ));
    for (i, rgb) in frames.iter().enumerate() {
        body.push_str(&format!("  {{ // {}\n", EXPR_IDS[i]));
        body.push_str(&fmt_bytes(rgb, 24));
        body.push_str("\n  },\n");
    }
    body.push_str("};\n\n");
    body.push_str("inline void copyFrame(uint8_t expr_index, uint8_t* dst) {\n");
    body.push_str("  if (dst == nullptr || expr_index >= kExprCount) return;\n");
    body.push_str("  memcpy_P(dst, kFrames[expr_index], static_cast<size_t>(kLedCount) * 3u);\n");
    body.push_str("}\n\n");
    body.push_str("inline void blendFrames(uint8_t from, uint8_t to, float w, uint8_t* dst) {\n");
    body.push_str("  if (dst == nullptr || from >= kExprCount || to >= kExprCount) return;\n");
    body.push_str("  if (w <= 0.0f) { copyFrame(from, dst); return; }\n");
    body.push_str("  if (w >= 1.0f) { copyFrame(to, dst); return; }\n");
    body.push_str("  const float a = 1.0f - w;\n");
    body.push_str("  const size_t bytes = static_cast<size_t>(kLedCount) * 3u;\n");
    body.push_str("  for (size_t i = 0; i < bytes; i++) {\n");
    body.push_str("    const uint8_t f = pgm_read_byte(kFrames[from] + i);\n");
    body.push_str("    const uint8_t t = pgm_read_byte(kFrames[to] + i);\n");
    body.push_str("    dst[i] = static_cast<uint8_t>(f * a + t * w + 0.5f);\n");
    body.push_str("  }\n");
    body.push_str("}\n\n");
    body.push_str("}  // namespace glowbe::local_mate\n");

    if let Some(parent) = out_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(out_path, body).with_context(|| format!("write {}", out_path.display()))?;
    eprintln!(
        "wrote {} ({} exprs × {} LEDs)",
        out_path.display(),
        EXPR_IDS.len(),
        n
    );
    Ok(())
}

pub fn bake_all() -> Result<()> {
    let root = repo_root();
    let compiled = root.join("assets/compiled");
    for layout_id in LAYOUTS {
        let out = root
            .join("firmware/esp32/include/generated")
            .join(layout_id)
            .join("glowbe_local_mate.h");
        bake_layout(&compiled, layout_id, &out)?;
    }
    Ok(())
}
