import type { Rig } from "../schema";
import { buildCalibration } from "./calibration";

/**
 * Generate the firmware layout header (`glowbe-layout.h`) so the ESP32 can
 * allocate buffers and configure the I2S driver without hardcoded magic numbers.
 */
export const generateLayoutHeader = (rig: Rig): string => {
  const cal = buildCalibration(rig);
  const channels = cal.channels;
  const pins = channels.map((c) => c.pin).join(", ");
  const counts = channels.map((c) => c.ledCount).join(", ");

  const channelBase: number[] = [];
  let base = 0;
  for (const c of channels) {
    channelBase.push(base);
    base += c.ledCount;
  }

  const offsets = cal.leds.map((led) => {
    const chBase = channelBase[led.address.channel] ?? 0;
    return (chBase + led.address.chainIndex) * 3;
  });
  const offsetLines: string[] = [];
  for (let i = 0; i < offsets.length; i += 16) {
    offsetLines.push(offsets.slice(i, i + 16).join(", "));
  }

  return `// AUTO-GENERATED by @glowbe/core. Do not edit by hand.
// Rig: ${cal.rigName} (${cal.rigId})
#pragma once

#include <stdint.h>

#define GLOWBE_SCHEMA_VERSION ${cal.schemaVersion}
#define GLOWBE_NUM_CHANNELS ${channels.length}
#define GLOWBE_TOTAL_LEDS ${cal.totalLeds}

static const int GLOWBE_PINS[GLOWBE_NUM_CHANNELS] = { ${pins} };
static const int GLOWBE_LEDS_PER_CHANNEL[GLOWBE_NUM_CHANNELS] = { ${counts} };

/** Byte offset in the I2S GRB buffer for each Studio globalIndex (FRAME RGB order). */
static const uint16_t GLOWBE_GLOBAL_OFFSET[GLOWBE_TOTAL_LEDS] = {
  ${offsetLines.join(",\n  ")}
};
`;
};
