// Auto-generated by tools/layout-compile.ts — do not edit.
#pragma once
#define GLOWBE_LAYOUT_ID "prototype-icosahedron-15"
#define GLOWBE_LAYOUT_HASH ((uint32_t)0x7c501117u)
#define GLOWBE_LED_COUNT 225
#define GLOWBE_DATA_LINES 5
static const uint8_t GLOWBE_GPIO_PINS[5] = { 16, 17, 18, 19, 21 };
static const uint16_t GLOWBE_LINE_LED_COUNTS[5] = { 45, 45, 45, 45, 45 };

// ESP32-S3: contiguous buffer + LCD DMA parallel (FastLED FASTLED_USES_ESP32S3_I2S).
#define GLOWBE_FASTLED_REGISTER_PARALLEL(leds) \
  FastLED.addLeds<WS2812, 16, GRB>((leds) + 0, 45); \
  FastLED.addLeds<WS2812, 17, GRB>((leds) + 45, 45); \
  FastLED.addLeds<WS2812, 18, GRB>((leds) + 90, 45); \
  FastLED.addLeds<WS2812, 19, GRB>((leds) + 135, 45); \
  FastLED.addLeds<WS2812, 21, GRB>((leds) + 180, 45);

// ESP32 (classic): per-line buffers + RMT per data pin.
#define GLOWBE_FASTLED_REGISTER_RMT(strips) \
  FastLED.addLeds<WS2812, 16, GRB>((strips)[0], 45); \
  FastLED.addLeds<WS2812, 17, GRB>((strips)[1], 45); \
  FastLED.addLeds<WS2812, 18, GRB>((strips)[2], 45); \
  FastLED.addLeds<WS2812, 19, GRB>((strips)[3], 45); \
  FastLED.addLeds<WS2812, 21, GRB>((strips)[4], 45);
