/**
 * Generate PROGMEM UV/dir tables for ESP offline playout.
 *
 *   npx tsx tools/esp-local-tables.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

/** Match Studio loop demos (device frontYaw applied at Runtime; offline uses raw ledmap UV). */
const FRONT_YAW_DEG = 0

const LAYOUTS = ['geodesic-2v-60', 'icosahedron-15'] as const

type Led = { i: number; u: number; v: number }

function applyYawU(u: number, yawDeg: number): number {
  let x = u - yawDeg / 360
  x = x - Math.floor(x)
  return x
}

function unitDirFromEquirect(u: number, v: number): [number, number, number] {
  const uu = ((u % 1) + 1) % 1
  const vv = Math.min(1, Math.max(0, v))
  const lambda = 2 * Math.PI * uu - Math.PI
  const phi = Math.PI / 2 - Math.PI * vv
  const cosPhi = Math.cos(phi)
  return [cosPhi * Math.cos(lambda), Math.sin(phi), cosPhi * Math.sin(lambda)]
}

function fmtF(arr: number[], perLine: number): string {
  const parts: string[] = []
  for (let i = 0; i < arr.length; i += perLine) {
    const slice = arr.slice(i, i + perLine).map((v) => {
      const s = v.toFixed(6)
      return s.includes('.') ? `${s}f` : `${s}.0f`
    })
    parts.push(`  ${slice.join(', ')},`)
  }
  return parts.join('\n')
}

function generate(layoutId: string) {
  const ledmapPath = join(root, 'assets', 'compiled', `${layoutId}.ledmap.json`)
  const raw = JSON.parse(readFileSync(ledmapPath, 'utf8')) as { leds: Led[] }
  const leds = [...raw.leds].sort((a, b) => a.i - b.i)
  const n = leds.length

  const uv: number[] = []
  const dir: number[] = []
  for (let i = 0; i < n; i++) {
    const led = leds[i] ?? { i, u: 0.5, v: 0.5 }
    const uYawed = applyYawU(led.u, FRONT_YAW_DEG)
    uv.push(uYawed, led.v)
    const d = unitDirFromEquirect(uYawed, led.v)
    dir.push(d[0], d[1], d[2])
  }

  const outPath = join(
    root,
    'firmware',
    'esp32',
    'include',
    'generated',
    layoutId,
    'glowbe_local_geom.h',
  )
  mkdirSync(dirname(outPath), { recursive: true })

  const body = `// Auto-generated by tools/esp-local-tables.ts — do not edit.
#pragma once

#include <Arduino.h>

namespace glowbe::local_geom {

constexpr uint16_t kLedCount = ${n};
constexpr float kFrontYawDeg = ${FRONT_YAW_DEG}.0f;

static const float kUv[kLedCount * 2] PROGMEM = {
${fmtF(uv, 8)}
};

static const float kDir[kLedCount * 3] PROGMEM = {
${fmtF(dir, 6)}
};

inline float uvU(uint16_t i) { return pgm_read_float(kUv + i * 2u); }
inline float uvV(uint16_t i) { return pgm_read_float(kUv + i * 2u + 1u); }
inline void dirAt(uint16_t i, float& x, float& y, float& z) {
  const uint32_t o = static_cast<uint32_t>(i) * 3u;
  x = pgm_read_float(kDir + o);
  y = pgm_read_float(kDir + o + 1u);
  z = pgm_read_float(kDir + o + 2u);
}

}  // namespace glowbe::local_geom
`
  writeFileSync(outPath, body)
  console.log(`Wrote ${outPath} (${n} LEDs)`)
}

for (const id of LAYOUTS) {
  generate(id)
}
