#!/usr/bin/env npx tsx
/**
 * Compile glowbe-layout v1 → UV map, binary meta, and firmware header.
 *
 * Usage:
 *   npx tsx tools/layout-compile.ts config/layouts/prototype.layout.json
 */
import {
  buildWiringFromChains,
  generateSolid,
  resolveRig,
  type FaceLayout,
  type Rig,
} from "../../archived-Glowbe/packages/core/src/index.ts";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const REPO = join(dirname(fileURLToPath(import.meta.url)), "..");

type GlowbeLayout = {
  format: "glowbe-layout";
  version: 1;
  id: string;
  displayName: string;
  variant: string;
  geometry: {
    preset: string;
    radiusMm: number;
    units: "mm";
    disabledFaceIds: string[];
  };
  face: {
    ledCount: number;
    pattern: FaceLayout["pattern"];
    paddingMm: number;
    chainMirrorLR: boolean;
    rowSizes?: number[];
  };
  wiring: {
    chip: string;
    colorOrder: string;
    dataLines: Array<{
      gpio: number;
      faceChain: string[];
      faceRotations: Record<string, number>;
      reversedFaces: string[];
    }>;
  };
};

function layoutToRig(layout: GlowbeLayout): Rig {
  const solid = generateSolid(
    layout.geometry.preset as Parameters<typeof generateSolid>[0],
    layout.geometry.radiusMm,
  );
  solid.disabledFaceIds = [...layout.geometry.disabledFaceIds];

  const faceLayout: FaceLayout = {
    faceType: "triangle",
    ledCount: layout.face.ledCount,
    pattern: layout.face.pattern,
    paddingMm: layout.face.paddingMm,
    padding: 0,
    chainEntry: 0,
    chainMirrorLR: layout.face.chainMirrorLR,
    ...(layout.face.rowSizes ? { rowSizes: layout.face.rowSizes } : {}),
  };

  const chains = layout.wiring.dataLines.map((d) => d.faceChain);
  const pins = layout.wiring.dataLines.map((d) => d.gpio);
  const reversed = layout.wiring.dataLines.flatMap((d) => d.reversedFaces);
  const faceRotations = Object.assign(
    {},
    ...layout.wiring.dataLines.map((d) => d.faceRotations),
  );

  const { parts, channels } = buildWiringFromChains({
    chains,
    pins,
    reversed,
    faceRotations,
  });

  return {
    meta: {
      id: layout.id,
      name: layout.displayName,
      schemaVersion: 1,
      units: "mm",
    },
    solid,
    faceLayouts: [faceLayout],
    parts,
    channels,
  };
}

function writeBin(
  path: string,
  gpios: number[],
  ledsPerLine: number[],
): void {
  const ledCount = ledsPerLine.reduce((a, b) => a + b, 0);
  const n = gpios.length;
  const buf = Buffer.alloc(8 + n + n * 2);
  buf.write("GBLD", 0, "ascii");
  buf.writeUInt8(1, 4);
  buf.writeUInt16LE(ledCount, 5);
  buf.writeUInt8(n, 7);
  for (let i = 0; i < n; i++) buf.writeUInt8(gpios[i]!, 8 + i);
  const off = 8 + n;
  for (let i = 0; i < n; i++) buf.writeUInt16LE(ledsPerLine[i]!, off + i * 2);
  writeFileSync(path, buf);
}

/** FNV-1a 32-bit — must match runtime `meta.layoutHash` for mismatch detection. */
function fnv1aLayoutHash(
  layout: GlowbeLayout,
  gpios: number[],
  ledsPerLine: number[],
): number {
  const canonical = JSON.stringify({
    id: layout.id,
    gpios,
    ledsPerLine,
    chip: layout.wiring.chip,
    colorOrder: layout.wiring.colorOrder,
  });
  let h = 0x811c9dc5;
  for (let i = 0; i < canonical.length; i++) {
    h ^= canonical.charCodeAt(i);
    h = Math.imul(h, 0x01000193) >>> 0;
  }
  return h >>> 0;
}

function writeHeader(
  path: string,
  layoutId: string,
  gpios: number[],
  ledsPerLine: number[],
  layoutHash: number,
): void {
  const ledCount = ledsPerLine.reduce((a, b) => a + b, 0);
  const h = layoutHash >>> 0;
  const hex8 = h.toString(16).padStart(8, "0");
  let offset = 0;
  const parallelLines = gpios.map((gpio, i) => {
    const n = ledsPerLine[i]!;
    const line = `  FastLED.addLeds<WS2812, ${gpio}, GRB>((leds) + ${offset}, ${n});`;
    offset += n;
    return line;
  });
  const rmtLines = gpios.map((gpio, i) => {
    const n = ledsPerLine[i]!;
    return `  FastLED.addLeds<WS2812, ${gpio}, GRB>((strips)[${i}], ${n});`;
  });
  const macro = (name: string, arg: string, body: string[]) => [
    `#define ${name}(${arg}) \\`,
    ...body.map((l, i) => (i < body.length - 1 ? `${l} \\` : l)),
    "",
  ];
  const lines = [
    "// Auto-generated by tools/layout-compile.ts — do not edit.",
    `#pragma once`,
    `#define GLOWBE_LAYOUT_ID "${layoutId}"`,
    `#define GLOWBE_LAYOUT_HASH ((uint32_t)0x${hex8}u)`,
    `#define GLOWBE_LED_COUNT ${ledCount}`,
    `#define GLOWBE_DATA_LINES ${gpios.length}`,
    `static const uint8_t GLOWBE_GPIO_PINS[${gpios.length}] = { ${gpios.join(", ")} };`,
    `static const uint16_t GLOWBE_LINE_LED_COUNTS[${gpios.length}] = { ${ledsPerLine.join(", ")} };`,
    "",
    "// ESP32-S3: contiguous buffer + LCD DMA parallel (FastLED FASTLED_USES_ESP32S3_I2S).",
    ...macro("GLOWBE_FASTLED_REGISTER_PARALLEL", "leds", parallelLines),
    "// ESP32 (classic): per-line buffers; `prototype-esp32` は FastLED I2S-parallel（platformio.ini）。",
    ...macro("GLOWBE_FASTLED_REGISTER_RMT", "strips", rmtLines),
  ];
  writeFileSync(path, lines.join("\n"), "utf8");
}

function main(): void {
  const input = process.argv[2];
  if (!input) {
    console.error("Usage: npx tsx tools/layout-compile.ts <layout.json>");
    process.exit(2);
  }

  const layout = JSON.parse(readFileSync(input, "utf8")) as GlowbeLayout;
  if (layout.format !== "glowbe-layout" || layout.version !== 1) {
    throw new Error("Expected glowbe-layout version 1");
  }

  const rig = layoutToRig(layout);
  const placements = resolveRig(rig);

  const ledsPerLine = layout.wiring.dataLines.map((_, ch) =>
    placements.filter((p) => p.address.channel === ch).length,
  );
  const gpios = layout.wiring.dataLines.map((d) => d.gpio);
  const lineGlobalOffset: number[] = [];
  let acc = 0;
  for (const n of ledsPerLine) {
    lineGlobalOffset.push(acc);
    acc += n;
  }

  const outDir = join(REPO, "assets/compiled");
  const fwInc = join(REPO, "firmware/esp32s3/include");
  mkdirSync(outDir, { recursive: true });
  mkdirSync(fwInc, { recursive: true });

  const id = layout.id;
  const layoutHash = fnv1aLayoutHash(layout, gpios, ledsPerLine);
  const meta = {
    layoutId: id,
    layoutHash,
    displayName: layout.displayName,
    variant: layout.variant,
    ledCount: placements.length,
    dataLineCount: gpios.length,
    gpios,
    ledsPerLine,
    lineGlobalOffset,
    chip: layout.wiring.chip,
    colorOrder: layout.wiring.colorOrder,
  };

  const ledmap = placements.map((p) => ({
    i: p.globalIndex,
    u: Math.round(p.uv.x * 1e6) / 1e6,
    v: Math.round(p.uv.y * 1e6) / 1e6,
    channel: p.address.channel,
    chainIndex: p.address.chainIndex,
  }));

  writeFileSync(join(outDir, `${id}.meta.json`), JSON.stringify(meta, null, 2) + "\n");
  writeFileSync(join(outDir, `${id}.ledmap.json`), JSON.stringify({ layoutId: id, leds: ledmap }, null, 2) + "\n");
  writeBin(join(outDir, `${id}.bin`), gpios, ledsPerLine);
  writeHeader(join(fwInc, "glowbe_layout.h"), id, gpios, ledsPerLine, layoutHash);

  console.log(`Compiled ${id}: ${placements.length} LEDs, ${gpios.length} data lines`);
  console.log(`  GPIO: ${gpios.join(", ")}`);
  console.log(`  per line: ${ledsPerLine.join(", ")}`);
  console.log(`  → assets/compiled/${id}.*`);
  console.log(`  → firmware/esp32s3/include/glowbe_layout.h`);
}

main();
